SELECT JOB_ID, COUNT(EMPLOYEE_ID) FROM employees GROUP BY JOB_ID;
SELECT MANAGER_ID, SALARY FROM employees WHERE SALARY = (SELECT MIN(SALARY) FROM employees);
SELECT DEPARTMENT_ID, SUM(SALARY) FROM employees GROUP BY DEPARTMENT_ID;
SELECT JOB_ID, AVG(SALARY) FROM employees WHERE JOB_ID NOT LIKE 'IT_PROG' GROUP BY JOB_ID;
SELECT JOB_ID, MAX(SALARY) FROM employees GROUP BY JOB_ID HAVING MAX(SALARY) >= 4000;
SELECT DEPARTMENT_ID, AVG(SALARY) FROM employees GROUP BY DEPARTMENT_ID HAVING COUNT(DEPARTMENT_ID) > 10;