SELECT FIRST_NAME, LAST_NAME, SALARY FROM employees WHERE SALARY > (SELECT SALARY FROM employees WHERE LAST_NAME LIKE 'Bull');
SELECT FIRST_NAME, LAST_NAME FROM employees WHERE DEPARTMENT_ID = 60;
SELECT FIRST_NAME, LAST_NAME FROM employees WHERE JOB_ID IN (SELECT JOB_ID FROM jobs WHERE JOB_TITLE LIKE '%MANAGER');
SELECT FIRST_NAME, LAST_NAME, SALARY FROM employees WHERE SALARY > (SELECT AVG(SALARY) FROM employees);
SELECT FIRST_NAME, LAST_NAME, SALARY FROM employees 
WHERE SALARY = (SELECT MIN_SALARY FROM jobs WHERE JOB_ID = employees.JOB_ID);
SELECT FIRST_NAME, LAST_NAME, SALARY FROM employees 
WHERE SALARY = (SELECT MIN(MIN_SALARY) FROM jobs);
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, (SELECT DEPARTMENT_NAME FROM departments WHERE DEPARTMENT_ID = employees.DEPARTMENT_ID) FROM employees;
SELECT * FROM (SELECT * FROM employees ORDER BY EMPLOYEE_ID DESC LIMIT 10) AS Last10Employees ORDER BY EMPLOYEE_ID ASC;